### ISSUE TITLE
SIGSEGV on attempt to create queue

### ISSUE THREAD

**Issue by velimir** [vsdmars/rmqctl#3]
```
$ rmqctl create queue -d my_durable_queue
done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13a34f9]

goroutine 1 [running]:
github.com/vsdmars/rmqctl/pkg.handleHTTPResponse(0x0, 0x14a3937, 0x6, 0x14a365a, 0x5, 0x1, 0x0)
	pkg/http.go:20 +0x1e9
github.com/vsdmars/rmqctl/pkg.createQueue(0xc0002bea00, 0xc0002f40b0, 0x0, 0x0)
	pkg/rmqapi_action.go:130 +0xd4
github.com/vsdmars/rmqctl/pkg.createQueueJob(0xc0002de420, 0x18, 0xc000200b60)
	pkg/rmqapi_job.go:19 +0xa1
gopkg.in/urfave/cli%2ev1.HandleAction(0x142dc40, 0x14be9b8, 0xc0002de420, 0xc0002de420, 0xc000200ef8)
	external/in_gopkg_urfave_cli_v1/app.go:488 +0x101
gopkg.in/urfave/cli%2ev1.Command.Run(0x14a365a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14b7d2c, 0x3f, 0x14a9039, ...)
	external/in_gopkg_urfave_cli_v1/command.go:210 +0x9a2
gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc0002b8340, 0xc0002de000, 0x0, 0x0)
	external/in_gopkg_urfave_cli_v1/app.go:379 +0x7ef
gopkg.in/urfave/cli%2ev1.Command.startApp(0x14a3937, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14a6724, 0xf, 0x14b8c34, ...)
	external/in_gopkg_urfave_cli_v1/command.go:298 +0x808
gopkg.in/urfave/cli%2ev1.Command.Run(0x14a3937, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14a6724, 0xf, 0x14b8c34, ...)
	external/in_gopkg_urfave_cli_v1/command.go:98 +0x1250
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002b8000, 0xc00001e050, 0x5, 0x5, 0x0, 0x0)
	external/in_gopkg_urfave_cli_v1/app.go:255 +0x687
github.com/vsdmars/rmqctl/pkg.Cmd(0x0, 0x0)
	pkg/cmd.go:694 +0x33e
github.com/vsdmars/rmqctl/cmd.Cmd(0x13a3720, 0xc000201f68)
	cmd/cmd.go:9 +0x22
main.main()
	main.go:10 +0x26
```

seems like tool tries to create a queue using HTTP endpoint, which is not available.

**Comment by vsdmars** [comment]
Thanks for the report!
The reason is due to https://github.com/vsdmars/rmqctl/blob/v1/pkg/rmqapi_action.go#L124
when connection failed, response handle is nullptr, which causing the problem.
Fixed in v1.0.11
best,
